export const BREADLET_CONFIG = {
  maxDailyMiningTokens: 2500,
  chestPrices: {
    space: 25,
    human: 25,
    artifact: 25,
    pixel: 25,
    combat: 25,
    blooktuber: 25,
    plushiePack: 150,
  },
  rarityOrder: ['Common', 'Uncommon', 'Rare', 'Epic', 'Legendary', 'Mythic', 'Chroma', 'Unique', 'Transcendent'],
  shinyWhitelist: ['Mars', 'Aztec Coin', 'Worker', 'Olive Grenade', 'Green Astronaut'],
  defaultLuck: 0,
  maxClanMembers: 25,
  marketplaceMaxPrice: 100000,
  premiumPromoCodes: ['youtube', 'release', 'welcomeback'],
  freeSpinPerDay: true,
} as const;

export const CHEST_DEFINITIONS = [
  {
    id: 'space-chest',
    name: 'Space Chest',
    price: 25,
    description: 'Cosmic drops from deep space.',
    pool: ['Mars', 'Earth', 'Star', 'Consolation', 'Eclipse', 'Alien', 'Star Ship'],
    rarity: 'Mythic',
    isRetired: false,
    active: true,
  },
  {
    id: 'human-chest',
    name: 'Human Chest',
    price: 25,
    description: 'Everyday heroes and legendary labor.',
    pool: ['Worker', 'Chef', 'Surgeon', 'Doctor', 'Ninja', 'Actor', 'Caveman'],
    rarity: 'Mythic',
    isRetired: true,
    active: false,
  },
  {
    id: 'lost-and-found-chest',
    name: 'Lost and Found Capsule',
    price: 25,
    description: 'Someone left these behind.',
    pool: ['Car Keys', 'Comb', 'Hat', 'Textbook', 'Tablet', 'Button'],
    rarity: 'Mythic',
    isRetired: false,
    active: true,
  },
  {
    id: 'food-chest',
    name: 'Food Capsule',
    price: 25,
    description: 'Snacks, a mystical pickle, and a rock as a joke.',
    pool: ['Rock', 'Apple', 'Fries', 'Egg', 'Candy Corn', 'Caramel', 'Sprinkle Bread', 'Ice Cream', 'Pickle'],
    rarity: 'Mythic',
    isRetired: false,
    active: true,
  },
  {
    id: 'artifact-chest',
    name: 'Artifact Chest',
    price: 25,
    description: 'Ancient relics and hidden mysteries.',
    pool: ['Aztec Coin', 'Map', 'Crystal Ball', 'Necklace', 'Stone Tablet', 'Time Glass'],
    rarity: 'Mythic',
    isRetired: false,
    active: true,
  },
  {
    id: 'pixel-chest',
    name: 'Pixel Chest',
    price: 25,
    description: 'Retro favorites and playful sprites.',
    pool: ['Pixel Apple', 'Pixel Caramel', 'Pixel Crystal Ball', 'Pixel Bomb', 'Pixel Constellation', 'Pixel Aztec Coin', 'Pixel Lagoon', 'Pixel Sprinkle Bread'],
    rarity: 'Mythic',
    isRetired: false,
    active: true,
  },
  {
    id: 'combat-chest',
    name: 'Combat Chest',
    price: 25,
    description: 'Combat gear and tactical power.',
    pool: ['Olive Grenade', 'The Bomb', 'Golden Grenade', 'Shuriken', 'Nunchucks', 'Spartan', 'Golden Shuriken'],
    rarity: 'Mythic',
    isRetired: false,
    active: true,
  },
  {
    id: 'blooktuber-chest',
    name: 'BlookTuber Chest',
    price: 25,
    description: 'Creator-themed collectibles.',
    pool: ['Bread Blook'],
    rarity: 'Mythic',
    isRetired: false,
    active: true,
  },
  {
    id: 'plushie-pack',
    name: 'Plushie Pack',
    price: 150,
    description: 'Limited plushie collection with a five-day availability window.',
    pool: ['Parrot Plushie', 'Blobfish Plushie', 'Dragon Plushie', 'Bronto Plushie', 'Cat Plushie', 'Arctic Hare Plushie'],
    rarity: 'Unique',
    isRetired: false,
    active: true,
  },
  {
    id: 'bread-chest',
    name: 'Bread Chest',
    price: 25,
    description: 'Retired collectible chest.',
    pool: ['Bread Blook'],
    rarity: 'Mythic',
    isRetired: true,
    active: false,
  },
  {
    id: 'remix-chest',
    name: 'Remix Chest',
    price: 25,
    description: 'Retired remix collection.',
    pool: ['Red Rex'],
    rarity: 'Transcendent',
    isRetired: true,
    active: false,
  },
] as const;
