insert into public.blooks (name, rarity) values
  ('Car Keys', 'Common'),
  ('Comb', 'Common'),
  ('Hat', 'Uncommon'),
  ('Textbook', 'Rare'),
  ('Tablet', 'Legendary'),
  ('Button', 'Mythic'),
  ('Rock', 'Common'),
  ('Apple', 'Common'),
  ('Potato', 'Common'),
  ('Fries', 'Uncommon'),
  ('Egg', 'Uncommon'),
  ('Carrot', 'Uncommon'),
  ('Candy Corn', 'Rare'),
  ('Avocado', 'Rare'),
  ('Caramel', 'Epic'),
  ('Sprinkle Bread', 'Epic'),
  ('Ice Cream', 'Legendary'),
  ('Pickle', 'Mythic'),
  ('Olive Grenade', 'Common'),
  ('The Bomb', 'Uncommon'),
  ('Golden Grenade', 'Rare'),
  ('Shuriken', 'Rare'),
  ('Nunchucks', 'Epic'),
  ('Spartan', 'Legendary'),
  ('Golden Shuriken', 'Mythic')
on conflict (name) do update set rarity = excluded.rarity;